# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba9cdffff7734b9b458b9dfe466dab7da84242e46ee555471947dac1488708f4632b41b0c700ec4ebd21bd6e4ae5e22b1b5720b276cb8d7aceea10dd5f96b3f

test:
  secret_key_base: 152874412ac15948af7d373daffa62d67bbed5fd12085ed2cb326047e79d670f2070580d13680085f17bfe72699528d4d5281cdf909740112681971dc342b009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
